
5. Set delicious account details setting page.
6. Indicate which links you wish to sync in delicious by tagging them as `sync`

Delicious tags are different to WordPress categories in that they are lower case and do not allow spaces. 
To allow for better looking tags in WordPress imported tags will have dashes and underscores replaces with space and the first letter of each word will be capitalised. 
